### ISSUE TITLE
API expects arguments for bytes32 parameters to be in hex

### ISSUE THREAD

**Issue by jdmaresco** [blockapps/bloc#2]
Solidity Contract:
![image](https://cloud.githubusercontent.com/assets/1327983/9292034/f8c93b3c-43af-11e5-9d09-0393016de04c.png)

Generated UI:
![image](https://cloud.githubusercontent.com/assets/1327983/9292031/e0264e08-43af-11e5-86f2-aee701142ca8.png)

Console Error:
![image](https://cloud.githubusercontent.com/assets/1327983/9292028/c5ad1a16-43af-11e5-8509-51e6360a20ee.png)

**Comment by kjameslubin** [comment]
Was fixed awhile ago...
