### ISSUE TITLE
Clean up install process in general

### ISSUE THREAD

**Issue by kjameslubin** [blockapps/bloc#20]

**Comment by jamshidh** [comment]
Business Story: partner developers and enterprise tech guys should be able to build a BlockApp without our intervention.
Experiment: get 5-10 webdevs, point them at the bloc git repo (and docs) and watch. 
Control: see if half of them can install truffle / ERIS / some competitor’s tool and build an app with them. Or, better, compare against building a rails app that hooks into a database, or a mobile app with Cordova

**Comment by kejace** [comment]
This takes days but in a low intensity way. Should use blockapps/customer-feedback to monitor the results. I'm not sure this should be prioritized before devcon - perhaps we do the study during devcon?

**Comment by kjameslubin** [comment]
This is sort of ongoing, but @kejace and @ryanreich need to get together to push the non-native code only fix through everything we use.

**Comment by kjameslubin** [comment]
It is pretty smooth now.
