### ISSUE TITLE
Make it easier to interact with existing contracts

### ISSUE THREAD

**Issue by kjameslubin** [blockapps/bloc#23]
This is not well explained at the moment

**Comment by jamshidh** [comment]
Is there something we might be able to do for this before DevCon?  If not, move to Future

**Comment by kjameslubin** [comment]
Yes, need to talk with @jcrain @kejace about concrete steps. Also see my comment on #25

**Comment by kjameslubin** [comment]
We've taken some concrete steps, but this feels like an ongoing issue. Moving to Future
