### ISSUE TITLE
scaffolded files should indicate whether or not their associated contract has been pushed to blockchain

### ISSUE THREAD

**Issue by kjameslubin** [blockapps/bloc#25]
bloc compile scaffolds the html files associated with a solidity contract but not the javascript files, as the javascript template depends directly on the contract address. The contract address is only set in stone at the bloc upload stage.

bloc previously didn't make it obvious that bloc upload mutated the associated `meta/<ContractName>.json` file. There was general confusion then as to:

1. what happens when you push new contracts and how to use that in an application.
2. how to interact with existing contracts that you've already pushed

So, a concrete step to make this more clear is that the scaffolded html files switch from some obviously labeled `contract status: not pushed` vs `contract status: pushed with address < TheAddress >`

**Comment by jamshidh** [comment]
Let's have a meeting to discuss this issue....

**Comment by kjameslubin** [comment]
also never had this meeting ^

**Comment by ryanreich** [comment]
This is about bloc, not blockapps-js, so I think this is actually for Kieren.

**Comment by kjameslubin** [comment]
This is related to #23. Added enhancement label
