### ISSUE TITLE
Error with JS API when returning a bytes32 value from a function

### ISSUE THREAD

**Issue by jdmaresco** [blockapps/bloc#3]
Something should be returned from this (we just set it):
![image](https://cloud.githubusercontent.com/assets/1327983/9292311/3722d8de-43bf-11e5-95a1-fbee41a9b501.png)

### Solidity
![image](https://cloud.githubusercontent.com/assets/1327983/9292315/6e728898-43bf-11e5-93db-78dbfc89a20c.png)

This function returns and the error below goes away when we change everything from storing a bytes32 to a uint. 

### Console log
![image](https://cloud.githubusercontent.com/assets/1327983/9292314/58632c06-43bf-11e5-895e-dcc22ac84bfe.png)

### Context
![image](https://cloud.githubusercontent.com/assets/1327983/9292319/a3f4f8e8-43bf-11e5-92c7-18858f2c8921.png)

**Comment by ryanreich** [comment]
Seems to have been fixed.  See the node interaction:
```js
> var lib = require("blockapps-js")
> lib.Solidity("contract C { function f() returns (bytes32) { return \"Hi!\"; } }")
  .call("newContract",
"1dd885a423f4e212740f116afa66d40aafdbb3a381079150371801871d9ea281")
  .get("state")
  .call("f").call("callFrom", "1dd885a423f4e212740f116afa66d40aafdbb3a381079150371801871d9ea281")]
  .then(console.log)
{ _bitField: 0,
  _fulfillmentHandler0: undefined,
  _rejectionHandler0: undefined,
  _progressHandler0: undefined,
  _promise0: undefined,
  _receiver0: undefined,
  _settledValue: undefined }
> <Buffer 48 69 21 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
```
