### ISSUE TITLE
After `npm install` - bloc crashes on windows 7

### ISSUE THREAD

**Issue by kejace** [blockapps/bloc#38]
```
C:\haskell\bloc\myapp>bloc start
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn gulp ENOENT
    at exports._errnoException (util.js:874:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:439:9)
    at process._tickCallback (node.js:353:17)
    at Function.Module.runMain (module.js:469:11)
    at startup (node.js:134:18)
    at node.js:961:3

C:\haskell\bloc\myapp>
```

**Comment by kejace** [comment]
Currently investigating if this also happens on OS X / Linux

**Comment by kjameslubin** [comment]
You just don't have `gulp` installed. Not sure how to add a global dependency. Need clearer messaging

**Comment by kejace** [comment]
This does not happen on OS X so I will assume that the issue is unique to Windows.

**Comment by kejace** [comment]
Ok. Shouldn't we just make `gulp` a dependency for `bloc`?

**Comment by kjameslubin** [comment]
It is. It just isn't a **global** dependency. Maybe I can figure that out

**Comment by kejace** [comment]
It seems it doesn't support that: http://stackoverflow.com/a/14657796

How about adding it as a dependency locally and then use the local "../bin/gulp" path ?

**Comment by kjameslubin** [comment]
seems to work with "./node_modules/gulp/bin/gulp.js". It's a possible solution...

**Comment by kejace** [comment]
Right - it should be included in every `bloc init`'d projects package.json so that `./node_modules/gulp/bin/gulp.js` is always available. Do you want me to make the fix?

**Comment by kjameslubin** [comment]
I suppose we should wait until the meeting.

**Comment by kejace** [comment]
I see that argument. But it prevents me to do more QA on Windows right now.

**Comment by kjameslubin** [comment]
Well fix it then. Or run just run `node app.js`

**Comment by jamshidh** [comment]
verify this is closed.

**Comment by kjameslubin** [comment]
Should be closed, still need to remind the user to `cd projname && npm install` after running `bloc init`. See also #64, #48.
