### ISSUE TITLE
Use a templating engine for HTML generation

### ISSUE THREAD

**Issue by jdmaresco** [blockapps/bloc#4]
It it would probably be smart to use a template engine to control HTML generation. Something like [Swig](http://paularmstrong.github.io/swig/) would probably be perfect for this. Could tackle #1 as part of this...

There's the added benefit that users could also customize the templates before scaffolding without diving into the source code.

**Comment by JoshKaufman** [comment]
I've been looking at that. will see if I can get something going in the next day or two.
