### ISSUE TITLE
bloc README doesn't make it clear what registering gets me

### ISSUE THREAD

**Issue by jamshidh** [blockapps/bloc#40]
I was a bit confused by what I was registering for, and why I needed two passwords....

In fact I put in a fake email, never verified, and everything else seemed to work anyway.

What do I (the developer) get in return for giving my email and registering?

**Comment by jamshidh** [comment]
and will the process work if I don't do this step?

**Comment by kjameslubin** [comment]
This is what I said I was going to remove from the README

**Comment by jamshidh** [comment]
Just remove it

**Comment by jamshidh** [comment]
remove from README and in block command line documentation

**Comment by kjameslubin** [comment]
fixed in @aeab3289681a21f870a0dcf7ed772ebbe9321b2c, @22b02906c8475732c9bd0be98348265dc6636fed, @bf86d8554916a978f8d9583bbb2150aec692aa35.
Not yet merged to master.
