### ISSUE TITLE
Page should display lack of private key

### ISSUE THREAD

**Issue by kejace** [blockapps/bloc#44]
Right now it shows ```You don't yet have a wallet. Use bloc genkey to create one. You need one to upload and run contracts!```

But it should also tell me that I forgot to run `bloc genkey` - alternatively catch the error in the JS and prompt me that way, or both.

**Comment by kjameslubin** [comment]
Should be fixed in blockapps/bloc@3239349f139543491c6875cee58f43e7764bcda3
