### ISSUE TITLE
bloc start

### ISSUE THREAD

**Issue by jamshidh** [blockapps/bloc#48]
Explore the `bloc start` feature and focus on it in the README.md quickstart guide. This allows you the eliminate the '-s' stuff which can be confusing. I can demo it for you if it is helpful.

**Comment by kejace** [comment]
This is probably fixed @jcrain ? Vote to close. Although perhaps we should still explain `-s`.

**Comment by kjameslubin** [comment]
Need to explain better still, but closing.

**Comment by arurao** [comment]
bloc start doesn't work. It doesnt throw any error but doesn't start the node either and just exits.

**Comment by ryanreich** [comment]
@arurao Is port 8000 available for binding?

**Comment by arurao** [comment]
@ryanreich : Thanks for your follow up. The issue has been resolved and I have edited my earlier comment for anyone else facing a similar issue.
