### ISSUE TITLE
Style bloc start feature

### ISSUE THREAD

**Issue by jamshidh** [blockapps/bloc#49]
Coordinate @jcrain styling the statuses from  the `bloc start` feature. E.g: "You don't have a wallet, create one with `bloc genkey`" on a branch. `gulp-express-server` is the preferred branch. If you run `bloc start` you'll see what I'm talking about - the text that appears at the top of the screen. Presentations will look much nicer with this.

**Comment by kjameslubin** [comment]
Duplicate of #78
