### ISSUE TITLE
Make the prompt simpler

### ISSUE THREAD

**Issue by jamshidh** [blockapps/bloc#55]
Make the prompt simpler: 
    - you should be able to `bloc init <projectname>` as well as `bloc init`
    - the default parameters should be hidden from the user. Perhaps as @ryanreich has built the `profile`- s, you could `bloc init --development` and `bloc init --deployment` and the defaults would be set intelligently.

**Comment by kejace** [comment]
@ryanreich Not sure what --deployment means here. Can you elaborate? Making a new issue (#95)
