### ISSUE TITLE
multiple login feature

### ISSUE THREAD

**Issue by jamshidh** [blockapps/bloc#59]
a multiple login feature, isomorphic to `bloc genkey`, to test multi-party contracts.
  > bloc altkey
    would write /alt/key1.json, and the /login route would need to have a dropdown of the available keys
   When this is done, make `SimpleMultiSig` into a full example, like `SimplePriceFeed` is now. (See /examples/(Simple)PriceFeed)

**Comment by kjameslubin** [comment]
Done awhile ago. Available in a different form elsewhere, as well.
